### ISSUE TITLE
Update compiler

### ISSUE THREAD

**Issue by justin-wesley** [kohsuke/github-api#357]
With JDK 5 being end of life for many many years, it is time to move to JDK 8. I think you should create a branch for JDK 8 and even JDK 9, so contributors can use the newer JDK.

**Comment by Shredder121** [comment]
The issue is, that class file formats are forwards compatible, so the lowest common denominator is in most cases the best pick.
On the other end of the scale, there are the new features, so it's balancing those two.

I'm getting the impression that the new features aren't that important to this project, or at least not more important than compatibility.

**Comment by oleg-nenashev** [comment]
If somebody proposes a change where Java 6 + is really required, I am sure it will be considered. I do not see much need in enforcing the version until that though it would be possible to refactor the code a bit

**Comment by KostyaSha** [comment]
To make closeable client? I think it easier to fork this library.

**Comment by oleg-nenashev** [comment]
> To make closeable client? I think it easier to fork this library.

It is a reasonable improvement. So just create a PR ;)

**Comment by kohsuke** [comment]
I agree with @oleg-nenashev 

Updating class file version first is like a cart before a horse. Let somebody propose a change that benefits from newer version of Java.
